from typing import List
from PIL import Image
from time import time_ns
from pseudoRNG import XorShift64, LCG64, MASK64, INV_2_64
import numpy as np


def read_abc(filename: str) -> List[tuple[int, int, int]]:
    """
    Read (a, b, c) parameter triples from a results file.

    This function parses a text file produced by the XorShift64 parameter
    sweep, where each line contains values of a, b, and c written in the
    format generated by the test routine. The extracted triples can then
    be reused for further analysis or testing.

    Parameters
    ----------
    filename : str
        Path to the file containing (a, b, c) entries.

    Returns
    -------
    list of tuple[int, int, int]
        List of (a, b, c) parameter triples.
    """
    triples = []
    with open(filename, "r") as f:
        for line in f:
            parts = line.replace(",", "").split()
            a = int(parts[2])
            b = int(parts[5])
            c = int(parts[8])
            triples.append((a, b, c))
    return triples


def read_ac(filename: str) -> List[tuple[int, int]]:
    """
    Read (a, c) parameter pairs from a results file.

    This function parses a text file produced by the LCG64 parameter sweep,
    where each line contains values of a and c written in the format generated
    by the test routine. The extracted parameter pairs can be reused for
    further analysis or testing.

    Parameters
    ----------
    filename : str
        Path to the file containing (a, c) entries.

    Returns
    -------
    list of tuple[int, int]
        List of (a, c) parameter pairs.
    """
    doubles = []
    with open(filename, "r") as f:
        for line in f:
            parts = line.replace(",", "").split()
            a = int(parts[2])
            c = int(parts[5])
            doubles.append((a, c))
    return doubles


def genImgXorShift64(triples) -> None:
    """
    Generate grayscale images from XorShift64 output for visual inspection.

    Each (a, b, c) parameter triple defines a XorShift64 generator. Successive
    RNG outputs are mapped to grayscale intensities and used to fill square
    pixel blocks, making structural artifacts or correlations visually apparent.

    Parameters
    ----------
    triples : iterable of tuple[int, int, int]
        Iterable of (a, b, c) shift parameter triples for XorShift64.
    """
    width = height = 200        # Number of blocks in each dimension
    box_size = 16               # Pixel size of each block
    seed = time_ns() | 1        # Odd seed to avoid degenerate state

    for a, b, c in triples:
        # Initialize RNG for given parameters
        rng = XorShift64(seed, a, b, c)

        # Image array (uint8 for grayscale values)
        img = np.empty((height * box_size, width * box_size), dtype=np.uint8)

        for i in range(height):
            for j in range(width):
                # Use the most significant 8 bits of the RNG output
                # and replicate it over a box_size × box_size block
                img[
                    i * box_size:(i + 1) * box_size,
                    j * box_size:(j + 1) * box_size
                ] = (rng.next() * 256) >> 64

        # Save image for visual analysis
        Image.fromarray(img, mode="L").save(
            f"../RandomNoises/xorShift64/{a}-{b}-{c}.png"
        )
        print(f"Successfully created {a=} {b=} {c=}")


def genImgLCG64(doubles: list[tuple[int, int]]) -> None:
    """
    Generate grayscale images from LCG64 output for visual inspection.

    Each (a, c) parameter pair defines a 64-bit linear congruential generator.
    Successive RNG outputs are mapped to grayscale intensities and used to fill
    square pixel blocks, allowing visual detection of lattice structures,
    correlations, or other artifacts characteristic of LCGs.

    Parameters
    ----------
    doubles : list[tuple[int, int]]
        List of (a, c) parameter pairs for LCG64.
    """
    width = height = 200        # Number of blocks in each dimension
    box_size = 16               # Pixel size of each block
    seed = time_ns() | 1        # Odd seed to avoid degenerate state

    for a, c in doubles:
        # Initialize RNG for given parameters
        rng = LCG64(seed, a, c)

        # Image array (uint8 for grayscale values)
        img = np.empty((height * box_size, width * box_size), dtype=np.uint8)

        for i in range(height):
            for j in range(width):
                # Use the most significant 8 bits of the RNG output
                # and replicate it over a box_size × box_size block
                img[
                    i * box_size:(i + 1) * box_size,
                    j * box_size:(j + 1) * box_size
                ] = (rng.next() * 256) >> 64

        # Save image for visual analysis
        Image.fromarray(img, mode="L").save(
            f"../RandomNoises/lcg64/{a}-{c}.png"
        )
        print(f"Successfully created {a=} {c=}")


if __name__ == "__main__":
    """
    Entry point for image-based RNG diagnostics.

    The following test runs generate grayscale images from previously
    validated RNG parameter sets. These images are intended for visual
    inspection of structural artifacts in the generator output.

    Runtime Notes
    -------------
    - Each image-generation function typically takes about 1–2 minutes
      to complete, depending on the number of parameter sets.
    - If the input files were produced by the full parameter sweeps:
        * xorShift64.txt may contain 3000+ (a, b, c) triples
        * lcg64.txt may contain 170+ (a, c) pairs
      Running the corresponding image generator will create one image
      per entry and store all outputs in the "RandomNoises/" directory.
    - Ensure sufficient disk space before running large batches.

    Test Runs
    ---------
    Uncomment the desired block to generate images.
    """
    start = time_ns()

    # --- LCG64 image generation ---
    # pairs = read_ac("../data/lcg64.txt")
    # genImgLCG64(pairs)          # Creates 170+ images and takes ~30-40sec to run

    # --- XorShift64 image generation ---
    # triples = read_abc("../data/xorShift64.txt")
    # genImgXorShift64(triples)   # Creates 3200+ images and takes ~10mins to run

    end = time_ns()
    print(f"Took {((end - start) / 1e9) / 60:.2f} min")
